site_name: lernOS für Organisationen
site_url: https://cogneon.github.io/

docs_dir: src

site_dir: ../docs/de

nav:
    - Vorwort: index.md
    - Grundlagen:
        - Ein zeitgemäßes Verständnis von Organisationen: 3-1-Ein-zeitgemaesses-Verstaendnis-von-Organisation.md
        - Veränderung von Organisationen: 3-2-Veraenderung-von-Organisation.md
        - Die Lernende Organisation und ihre Feinde: 3-3-Die-Lernende-Organisation-und-ihre-Feinde.md
        - Eine Lernende Organisation kultivieren: 3-4-Eine-Lernende-Organisation-kultivieren.md
    - Lernpfad:
        - Lernpfad: 4-Lernpfad.md
    - Anhang:
        - Anhang: 5-Anhang.md
    - lernos.org: 'http://lernos.org'
theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-for-organizations'
repo_url: 'https://github.com/cogneon/lernos-for-organizations'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/lern_os
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/showcase/lern-os
        - icon: fontawesome/brands/github
          link: https://github.com/cogneon
    disqus: lernos
