site_name: lernOS für Organisationen
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Vorwort: index.md
    - Grundlagen:
        - Ein zeitgemäßes Verständnis von Organisationen: 3-1-Ein-zeitgemaesses-Verstaendnis-von-Organisation.md
        - Veränderung von Organisationen: 3-2-Veraenderung-von-Organisation.md
        - Die Lernende Organisation und ihre Feinde: 3-3-Die-Lernende-Organisation-und-ihre-Feinde.md
        - Eine Lernende Organisation kultivieren: 3-4-Eine-Lernende-Organisation-kultivieren.md
    - Lernpfad:
        - Lernpfad: 4-Lernpfad.md
    - Anhang:
        - Anhang: 5-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-for-organizations/blob/master/de/lernOS-Guide-for-Organizations-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-for-organizations/blob/master/de/lernOS-Guide-for-Organizations-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-for-organizations/blob/master/de/lernOS-Guide-for-Organizations-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-for-organizations/blob/master/de/lernOS-Guide-for-Organizations-de.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-for-organizations/blob/master/de/lernOS-Guide-for-Organizations-de.mobi
    - Links:
      - lernOS Website: https://lernos.org
      - lernOS Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-for-organizations'
repo_url: 'https://github.com/cogneon/lernos-for-organizations'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/lern_os
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/showcase/lern-os
        - icon: fontawesome/brands/github
          link: https://github.com/cogneon
    disqus: lernos
    analytics:
       provider: custom

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
